# Generated by Django 4.2.4 on 2023-08-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
